name: hello-world
on: push
jobs:
  firstjob:
     runs-on: ubuntu-latest
     steps:
         - name: Printing my name
           run: echo "Hi Priyanka, Welcome to GitHub Actions"
         - name: Print Github Repository
           run: echo $env:GITHUB_REPOSITORY
         - name: Print GitHub Workspace
           run:  echo $env:GITHUB_WORKSPACE
         - name: Print GitHub Workflow Name
           run:  echo $env:GITHUB_WORKFLOW
         - name: Print GitHub Workflow Initiator
           run:  echo $env:GITHUB_ACTOR
         - name: Print GitHub Runner Name
           run:  echo $env:RUNNER_NAME
         - name: Print GitHub Runner OS
           run:  echo $env:RUNNER_OS
